### ISSUE TITLE
incorrect test written for uniq

### ISSUE THREAD

**Issue by natedogg2090** [learn-co-students/js-advanced-functions-functional-library-project-v-000#15]
The test for removing duplicates after an iteratee is incorrect. The callback function is tests for a number divisible by 3 and the expected return is [1, 2, 3]. Since 3 divisor 3 is equal to 0 the expected array for the test should actually be [1, 2, 4] eliminating the extra 2 in the beginning array and the values  that pass the callback.

Additionally, there is a console.log statement left in the same test - [link](https://github.com/learn-co-students/js-advanced-functions-functional-library-project-v-000/blob/fa6c9996c9f842e817cf05d8e78d2c2f3a645e56/test/indexTest.js#L245)

**Comment by jmb521** [comment]
I disagree. The 3 divisor 3 is not an issue. 
Here is the result of running the callback 
[1, 2, 2, 0, 1, 0, 0]
What they are looking for are the original elements where the results are not duplicates. Meaning since 1 % 3 = 1 and 2 %3 = 2 and 3 % 3 = 0, the other numbers duplicate those results. 
Thus the tests are correct.

**Comment by natedogg2090** [comment]
I understand now thanks.
